-- local lspconfig = require "lspconfig"

-- lspconfig.util.default_config = vim.tbl_deep_extend("force", lspconfig.util.default_config, {
--     handlers = {
--         ["textDocument/hover"] = vim.lsp.with(vim.lsp.handlers.hover, {
--             border = vim.g.border_bleed, max_width = 80
--         }),
--         ["textDocument/signatureHelp"] = vim.lsp.with(vim.lsp.handlers.signature_help, {
--             border = vim.g.border_bleed, max_width = 80
--         })
--     },
--     capabilities = pcall(require, "cmp_nvim_lsp") and
--         package.loaded.cmp_nvim_lsp.default_capabilities() or nil
-- })
--
-- require("lspconfig.ui.windows").default_options.border = vim.g.border -- :LspInfo
