[alias]
clippy-all = [
  "clippy",
  "--",
  "--no-deps", # run Clippy only on the given crate
  # Deny, Warn, Allow, Forbid
  "-Wclippy::correctness", # code that is outright wrong or useless
  "-Wclippy::complexity",  # code that does something simple but in a complex way
  "-Wclippy::suspicious",  # code that is most likely wrong or useless
  "-Wclippy::style",       # code that should be written in a more idiomatic way
  "-Wclippy::perf",        # code that can be written to run faster
  "-Wclippy::pedantic",    # lints which are rather strict or have occasional false positives
  "-Wclippy::nursery",     # new lints that are still under development
  "-Aclippy::cargo",       # lints for the cargo manifest
  "-Aclippy::restriction", # lints which prevent the use of language and library features
  # Specific
  "-Aclippy::must_use_candidate",           # must_use is rather annoing
  "-Aclippy::cognitive_complexity",
  "-Aclippy::too_many_lines",
  "-Aclippy::missing_errors_doc",
  "-Aclippy::from_iter_instead_of_collect", # formats better

]

[build]
rustc-wrapper = "sccache"
rustflags = ["-Z", "threads=8"]


[profile.release]
lto = true

[profile.dev]
opt-level = 1
debug = "line-tables-only"
# codegen-backend = "cranelift"
# [unstable]
# codegen-backend = true

[profile.dev.package."*"]
opt-level = 3
debug = false
[profile.dev.build-override]
opt-level = 3

[profile.debugging]
inherits = "dev"
opt-level = 0
debug = true
lto = false


[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=wild"]
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"] # "target-cpu=native"
